version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Contacts-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app-network

  contacts-api:
    build: .
    container_name: contacts-api
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
    depends_on:
      - postgres
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
